name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "hello world!"
      - name: my-second-step
        run: echo "hello again!"
  new-job:
    runs-on: ubuntu-latest
    steps:
      - name: new-step
        run: echo "this is a new job!"
    
    
